/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;


import com.mycompany.proyectofinal.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author suris
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
    }
     public static Usuario usuario;
    public static Feed feed;
    
     public static void InsertarDatosArchivos () throws FileNotFoundException {
        
        String file = "C:\\Users\\suris\\OneDrive\\Escritorio\\ENTREGAEP2FINAL-main\\ProyectoFinal";
        int i=0;
        
        try{
         
         File archivo=new File(file);
         System.out.println(archivo.getAbsolutePath());
         Scanner scanner = new Scanner(archivo);
         
         while (scanner.hasNext()) {
            String []datos=scanner.next().split(";");
            System.out.print("Linea "+i + " Titulo:"+datos[0]);
            System.out.print(" Numero:"+datos[1]);
            System.out.print(" Descripcion:"+datos[2]);
            System.out.print(" HoraCreacionTarea:"+datos[3]);
            System.out.println(" PrioridadTarea:"+datos[4]);
            System.out.println(" EstadoTarea:"+datos[4]);
            i++;
         }
          scanner.close();
     }catch (FileNotFoundException e) {
        e.printStackTrace();
    }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        textField1 = new java.awt.TextField();
        nombreUsuarioInput = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jButton1 = new javax.swing.JButton();
        PasswordInput = new javax.swing.JPasswordField();

        textField1.setText("textField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));

        label1.setBackground(new java.awt.Color(255, 153, 255));
        label1.setText("Iniciar sesión");

        label2.setBackground(new java.awt.Color(255, 204, 255));
        label2.setText("Usuario");

        label3.setBackground(new java.awt.Color(255, 204, 255));
        label3.setText("Clave");

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 102, 204));
        jButton1.setText("Ingresar");
        jButton1.setAutoscrolls(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreUsuarioInput, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1))
                    .addComponent(PasswordInput))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreUsuarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(nombreUsuarioInput.getText().equals("Benja")&&PasswordInput.getText().equals("1234")){
            JOptionPane.showMessageDialog(rootPane, "Entraste, bienvenido");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "contraseña o usuario incorrecto");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
         InsertarDatosArchivos();
         
         int tamanyo=5;
         
         Tarea[] tareas=new Tarea[tamanyo];
         
         for(int i=0; i<tareas.length; i++){
             tareas[i]=new Tarea();
             tareas[i].setTitulo("Estudiar Fisica");
             tareas[i].setDescripcion("Estudiar 2 horas");
             tareas[i].setEstadoTarea("incompleta");
             tareas[i].setHoraCreacionTarea(13.05);
             tareas[i].setNumero(1);
             tareas[i].setPrioridadTarea("alta");
             
         }
         
         System.out.println("Tarea: "+tareas[0].getTitulo());
         
    
             Dia dia= new Dia();
             dia.setCalificacionDia(5);
             dia.setConsejoDeProductividad("Organiza una tarea grande en pequeñas tareas");
             dia.setNombreDia("Miercoles");
             dia.setFechaDia("25/03/23");
             
         
          System.out.println("Dia: "+dia.getNombreDia());
   
          Publicacion[] publicaciones=new Publicacion[tamanyo];
          for(int i=0; i<publicaciones.length; i++){
              
              publicaciones[i]=new Publicacion();
              publicaciones[i].setFechaPublicacion("24/09/23");
              publicaciones[i].setIdUsuarioPublicacion(456);
              publicaciones[i].setPrivacidadPublicacion("Publico");
              publicaciones[i].setSumaInteraccionPositiva(1);
              publicaciones[i].setSumaInteraccionNegativa(0);
              
          }
          
          ListaDeTareasPorHacer listaTareas=new ListaDeTareasPorHacer();
          listaTareas.setIdLista(425);
          
          Usuario[] usuarios=new Usuario[tamanyo];
          for(int i=0; i<usuarios.length;i++){
              usuarios[i]=new Usuario();
              usuarios[i].setAlias("Pepe");
              usuarios[i].setDescripcionPerfil("Persona feliz");
              usuarios[i].setFechaCreacionDeLaCuenta("24/08/23");
              usuarios[i].setIdUsuario(345);
              usuarios[i].setNombre("Pedro");
          }
          
          
          Calendario calendario = new Calendario();
          calendario.setAnyoCalendario(2023);
          calendario.setIdCalendario(1);
          Scanner leer = new Scanner(System.in);
          //menu
          int opc = 0;
          do{
              System.out.println("opcion 1 para agregar dia al calendario");
              System.out.println("opcion 2 para modificar año del calendario");
              System.out.println("opcion 3 para eliminar dia del calendario");
              System.out.println("opcion 4 para mostrar calendario");
              System.out.println("opcion 0 para SALIR");
              
              switch (opc){
                    case 1: 
                        if(calendario.buscarDia(calendario.getDiasCalendario(), dia) == false){
                            calendario.agregarDia(dia);
                            System.out.println("El dia ha sido agregado");
                        }
                            
                        break;
                    case 2: 
                        int anyoNuevo;
                        
                        System.out.println("ingresa el año del calendario");      //anyo
                        anyoNuevo = leer.nextInt();
                        calendario.modifCalendario(anyoNuevo);
                        System.out.println("El calendario ha sido actualizado");
                        break;
                    case 3:
                        if(calendario.buscarDia(calendario.getDiasCalendario(), dia) == true)
                            calendario.eliminarDia(dia);
                            System.out.println("Se ha eliminado un dia");
                        break;
                    case 4:
                        System.out.println("Mostrando calendario: ");
                        calendario.mostrarCalendario();
                        break;
                        
                    default:
                        System.out.println("Opcion no válida");
                        
                        break;
            }
       
          
          }while(opc!=0);
          
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField nombreUsuarioInput;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
